website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from .models import User
from werkzeug.security import check_password_hash
from . import db
from flask_login import login_user, login_required, current_user, logout_user, LoginManager
from .forms import LoginForm, RegisterForm, ProfilePictureForm
from .utils.token import confirm_token, generate_token
from .utils.decorators import logout_required
from datetime import datetime
from .utils.functions import flash_errors
from .utils.mail import send_confirm_email
from werkzeug.utils import secure_filename
from werkzeug.datastructures import  FileStorage
import os


auth=Blueprint('auth', __name__)

login_manager = LoginManager()



@auth.route('/login', methods=['POST', 'GET'])
@logout_required
def login():

    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate():
        email = form.email.data
        password = form.password.data
        remember = form.remember_me.data

        user = User.query.filter_by(email=email).first()

        if not user or not check_password_hash(user.password, password):
            flash('Please check your login details and try again.', 'error')
            return redirect(url_for('auth.login'))
        
        login_user(user, remember=remember)

        return redirect(url_for('views.userpage', userid=user.id))

    flash_errors(form)
    return render_template('login.html', form=form)



@auth.route('/signup', methods=['GET', 'POST'])
@logout_required
def signup():
    form = RegisterForm(request.form)
    profile_picture_form = ProfilePictureForm()

    if request.method == 'POST' and form.validate() and profile_picture_form.validate_on_submit():
        email=form.email.data
        
        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email address already exists', 'error')
            return redirect(url_for('auth.signup'))
        if len(form.username.data) > 15:
            flash('Username cannot be longer than 15 characters', 'error')
            return redirect(url_for('auth.signup'))
        
        picture_file = profile_picture_form.profile_picture.data

        if picture_file:
            filename = secure_filename(picture_file.filename)
            filepath = os.path.join(current_app.root_path, 'static/profile_pics', filename)
            picture_file.save(filepath)
        else:
            filename = "default_pfp.jpg"

        new_user = User(form.email.data, form.username.data,
                    form.password.data, is_confirmed=True, profile_picture=filename)

        db.session.add(new_user)
        db.session.commit()
        
        #email confirmation
        
        #!!!! zrezygnowalismy z funkcji potwierdzania maila, bo juz drugi raz nam zbanowali konto :(
        #!!!! ale generalnie dziala :))
        '''
        token = generate_token(new_user.email)
        confirm_url = url_for("auth.confirm_email", token=token, _external=True)
        html = render_template("confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_confirm_email(new_user.email, subject, html)
        
        login_user(new_user)

        flash("A confirmation email has been sent via email.", "happy")
        return redirect(url_for("auth.inactive"))
        '''
        
        flash("Thanks for registering!", "happy")
        return redirect(url_for('auth.login'))
        
        
    flash_errors(form)
    flash_errors(profile_picture_form)
    return render_template('signup.html', form=form, pfp_form=profile_picture_form)
    

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

'''
@auth.route("/confirm/<token>")
def confirm_email(token):
    if current_user.is_confirmed:
        flash("Account already confirmed.", "info")
        return redirect(url_for('views.userpage', userid=current_user.id))
    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.activated_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash("You have confirmed your account. Thanks!", "happy")
    else:
        flash("The confirmation link is invalid or has expired.", "error")
    return redirect(url_for('views.userpage', userid=user.id))


@auth.route("/inactive")
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for('views.userpage', userid=current_user.id))
    return render_template("inactive.html")
    
@auth.route("/resend_confirmation")
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash("Your account has already been confirmed.", "info")
        return redirect(url_for('views.userpage', userid=current_user.id))
    token = generate_token(current_user.email)
    confirm_url = url_for("auth.confirm_email", token=token, _external=True)
    html = render_template("confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_confirm_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.", "happy")
    return redirect(url_for("auth.inactive"))

'''

website/views.py
from flask import Blueprint, render_template, request, abort, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import User, Game
from . import db
from flask_mailman import EmailMessage
from flask_login import current_user
from .utils.decorators import active_login_required
from .forms import SearchUserForm
from datetime import datetime
from .models import Comment
from .forms import CommentForm
from flask_sqlalchemy import SQLAlchemy 
from sqlalchemy.sql import func

views=Blueprint('views', __name__)
usersbp=Blueprint('users', __name__)

@views.route('/')
def index():
    return render_template('index.html')

@views.route('/users', methods=['GET', 'POST'])
@active_login_required
def users():
    form = SearchUserForm(request.form)
    if request.method == 'POST':
        username = form.search.data
        if username:
            users = User.query.filter(User.name.like(f'%{username}%')).filter_by(is_confirmed=True).all()
        else:
            users = User.query.filter_by(is_confirmed=True).all()
    else:
        users = User.query.filter_by(is_confirmed=True).all()
    return render_template('users.html', users=users, form=form)

@views.route('/play')
@active_login_required
def play():
    return render_template('game.html')

@views.route("/user/<int:userid>", methods=['GET', 'POST'])
@active_login_required
def userpage(userid):
    user = User.query.get(userid)

    game_count = Game.query.filter_by(user_id=userid).count()

    highest_score = Game.query.filter_by(user_id=userid).order_by(Game.score.desc()).first()
    high_score = highest_score.score if highest_score else 0

    if user is None or not user.is_confirmed:
        abort(404)
        
    user_comments = Comment.query.filter_by(user_to_id=user.id)
    comment_form = CommentForm()
   
    if request.method == 'POST' and comment_form.validate():
        print(comment_form.comment.data, datetime.now(), user.id, current_user.id)
        new_comment = Comment(body=comment_form.comment.data, timestamp=datetime.now(), 
                user_to_id=user.id, user_from_id=current_user.id, user_from_name=current_user.name)
        print(new_comment)
        db.session.add(new_comment)
        db.session.commit()
    
    print("testestst")
    return render_template('userpage.html', user=user, high_score=high_score, game_count=game_count, comments=user_comments, form = comment_form)


AUTH_TOKEN = "gordini_wysyla_wynik"
@views.route('/receive_score', methods=['POST'])
@active_login_required
def receive_score():
    try:
        auth_token = request.headers.get('Authorization')
        if auth_token != AUTH_TOKEN:
            abort(401)

        score = request.form.get('score')
        userid = current_user.id 

        new_game = Game(user_id=int(userid), score=int(score))
        db.session.add(new_game)
        db.session.commit()

        return jsonify({"status": "success"}), 200
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

@views.route('/leaderboard')
def leaderboard():
    
    subquery = (
        db.session.query(
            Game.user_id,
            func.max(Game.score).label('max_score')
        )
        .group_by(Game.user_id)
        .subquery()
    )

    games_list = (
        db.session.query(
            User.id,
            User.name,
            subquery.c.max_score
        )
        .join(subquery, User.id == subquery.c.user_id)
        .order_by(subquery.c.max_score.desc()).all()
    )

    #for user_id, user_name, max_score in games_list:
    #    print(f'User ID: {user_id}, User Name: {user_name}, Max Score: {max_score}')
    

    return render_template('leaderboard.html', list=games_list)

'''
@views.route('/addgame')
def addgame():
    new_game = Game(2, 5)
    db.session.add(new_game)
    db.session.commit()
    return redirect(url_for('views.index'))
'''

website/templates/_formhelpers.html
{% macro render_field(field) -%}

{% set with_label = kwargs.pop('with_label', False) %}
{% set placeholder = kwargs.pop('placeholder', field.label.text) %}
{% set class_ = kwargs.pop('class_', '') %}

{% if field.flags.required %}
{% set class_ = class_ + ' required' %}
{% endif %}

<div class="form-group{% if field.errors %} error{% endif %}">

    {% if with_label %}
    <label for="{{ field.id }}"
           class="control-label{% if field.flags.required %} required{% endif %}">
        {{ field.label.text }}
    </label>
    {% endif %}

    {% if field.type == 'BooleanField' %}
    <div class="checkbox">
        {{ field(class_=class_, **kwargs) }}
        {{ field.label.text|safe }}
    </div>
    {% elif field.type == 'PasswordField' %}
        {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
       
    {% else %}
    {% if field.type in ('StringField', 'EmailField', 'TextField', 'TextAreaField', 'IntegerField') %}
    {% set class_ = class_ + ' input is-large' %}
    {% elif field.type == 'FileField' %}
    {% set class_ = class_ + ' input-file form-control' %}
    {% endif %}
    {% if field.type in('SelectField', 'BooleanField') %}
    {{ field(class_=class_, **kwargs) }}
    {% else %}
    {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
    {% endif %}
    {% endif %}

    {% if field.description %}
    <p class="help-block">{{ field.description|safe }}</p>
    {% endif %}

</div>


{%- endmacro %}

website/templates/base.html
<html lang="en">
<html lang="en">
<head>
    <title>SpikeClick</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href=" {{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />  <!------>
       
</head>
<script type=text/javascript src="{{
    url_for('static', filename='/main.js')
  }}"></script>
<body>
    <nav>
        <div class="navbar-set" id="navbar-set-left">
            <div class="navbar-logo">
                <span class="material-symbols-outlined" id="navbar-icon">
                    joystick
                </span>
            </div>
            <div class="navbar-logo">
                SPIKECLICK
            </div>
        </div>
        <a href="{{ url_for('views.play') }}">
            <div class="navbar-play">
                PLAY
            </div>
        </a>
        <div class="navbar-set" id="navbar-set-right">
            <a href="{{ url_for('views.index') }}" class="navbar-page-link">
                <span class="material-symbols-outlined" id="navbar-icon">
                    home
                </span>
            </a>
            <a href="{{ url_for('views.leaderboard') }}" class="navbar-page-link">
                <span class="material-symbols-outlined" id="navbar-icon">
                    trophy
                </span>
            </a>
            <a href="{{ url_for('views.users') }}" class="navbar-page-link">
                <span class="material-symbols-outlined" id="navbar-icon">
                    groups
                </span>
            </a>
            {% if not current_user.is_authenticated %}
                <a href="{{ url_for('auth.login') }}" class="navbar-page-link">
                    <span class="material-symbols-outlined" id="navbar-icon">
                        person
                    </span>
                </a>
            {% else %}
                <a href="{{ url_for('views.userpage', userid=current_user.id) }}" class="navbar-page-link">
                    <span class="material-symbols-outlined" id="navbar-icon">
                        person
                    </span>
                </a>
            {% endif %}
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}" class="navbar-page-link">
                    <span class="material-symbols-outlined" id="navbar-icon">
                        logout
                    </span>
                </a>
            {% endif %}
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% set message = messages[0] %}
            {% if message[0] == "happy" %}
                <div class="message-box-box">
                    <div class="message-box message-box-happy">
                        <span class="material-symbols-outlined" id="message-icon">
                            sentiment_very_satisfied
                        </span>
                        <div>
                            {{ message[1] }}
                         </div>
                     </div>
                 </div>
                 
            {% elif message[0] == "info" %}
                <div class="message-box-box">
                    <div class="message-box message-box-info">
                        <span class="material-symbols-outlined" id="message-icon">
                            info
                        </span>
                        <div>
                            {{ message[1] }}
                        </div>
                    </div>
                </div>
            {% elif message[0] == "error" %}
                <div class="message-box-box">
                    <div class="message-box message-box-error">
                        <span class="material-symbols-outlined" id="message-icon">
                            error
                        </span>
                        <div>
                            {{ message[1] }}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endwith %}


    {% block content %}
    {% endblock %}
</body>
</html>

website/templates/confirm_email.html
<!-- <a href="{{ confirm_url }}">{{ confirm_url }}</a> -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href=" {{ url_for('static', filename='style.css') }}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />


<div class="email-box">
    <div class="email-text">
        Hello there, <br>
        we recieved a request to create account linked with this e-mail adress. If you want to create account on adres.com click this button below:
    </div>
    <div class="email-button-box">
        <a href="{{ confirm_url }}">
            <div class="email-button">
                CONFIRM EMAIL
            </div>
        </a>
        <img class="email-image" src="">
    </div>
    <div class="email-footer">
        If you weren't trying to create an account on adres.com, ignore this email. <br>
        Spike Click media team
    </div>
</div>

website/templates/game.html
{% extends "base.html" %}

{% block content %}
<script type=text/javascript src="{{
    url_for('static', filename='/game-size.js')
  }}"></script>

<div class="game-box" id="game-box">
    <iframe class="game-frame" src="{{ url_for('static', filename='raw_game.html') }}"></iframe>
</div>
{% endblock %}

website/templates/inactive.html
{% extends "base.html" %} {% block content %}

{% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="error-box">
        <span class="material-symbols-outlined" id="error-icon">
            error
        </span>
        <div>
            {{ messages[0] }}
        </div>
    </div>
{% endif %}
{% endwith %}

<div class="text-center">
  <h1>Welcome!</h1>
  <br />
  <p>
    You have not confirmed your account. Please check your inbox (and your spam
    folder) - you should have received an email with a confirmation link.
  </p>
  <p>
    Didn't get the email?
    <a href="{{ url_for('auth.resend_confirmation') }}">Resend</a>.
  </p>
</div>

{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="home-text">
    PLAY THE BEST <br> REACTION GAME
</div>
<a href="{{ url_for('views.play') }}">
    <div class="navbar-play" id="home-button">
        PLAY
    </div>
</a>
<img src="../static/Image/spike.png" alt="spike" id="home-spike">
{% endblock %}

website/templates/leaderboard.html
{% extends "base.html" %}
{% block content %}

<div class="users-box">
    <div class="users-title">
        LEADERBOARD
    </div>
    <div class="users-line"></div>

    <table class="users-table">
        <thead class="users-table-head">
            <tr>
                <th>Username</th>
                <!-- <th>Email</th> -->
                <th>Top Score</th>
            </tr>
        </thead>
        <tbody>
            {% for user_id, user_name, max_score in list %}
            <tr>
                <td><a class="users-profilelink" href="{{ url_for('views.userpage', userid=user_id) }}">{{ user_name }}</a></td>
                <td>{{ max_score }}</a></td>
            </tr>
            {% endfor %}<!---->
        </tbody>
    </table>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
<div class="login-box">
    <div class="login-title">
        LOGIN
    </div>
    <div class="login-line"></div>

    <form class="login-form" role="form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="login-input-box">
            {{ render_field(form.email) }}
        </div>
        <div class="login-input-box">
            {{ render_field(form.password) }}
            <button class="login-show-password-button" type="button" onclick="togglePasswordVisibilityLogin('password')">
                <span class="material-symbols-outlined" id="key-icon">
                    visibility
                </span>
            </button>
        </div>

        <div class="login-rememberme-box">
            {{ render_field(form.remember_me) }}
        </div>


        <div class="login-button-box">
            <button class="login-button" id="login-button-login">
                LOGIN
            </button>
            <a href="{{ url_for('auth.signup') }}" class="login-button" id="login-button-register">
                SIGN UP
            </a>
        </div>
    </form>
</div>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}
{% block content %}

<h1>
  Welcome, {{name}}!
</h1>

{% if current_user.is_admin %}
<h1> 
Jestes sigmom
</h1>
{% endif %}
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
<div class="login-box">
    <div class="login-title">
        SIGN UP
    </div>
    <div class="login-line"></div>

    <form role="form" method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ pfp_form.csrf_token }}
        {{ form.hidden_tag() }}
        {{ pfp_form.hidden_tag() }}
        <div class="login-input-box">
            {{ render_field(form.email) }}
        </div>
        <div class="login-input-box">
          {{ render_field(form.username) }}
        </div>
        <div class="login-input-box">
            {{ render_field(form.password) }}
            <button class="login-show-password-button" type="button" onclick="togglePasswordVisibilitySignup('password', 'confirm')">
                <span class="material-symbols-outlined" id="key-icon">
                    visibility
                </span>
            </button>
        </div>
        <div class="login-input-box">
            {{ render_field(form.confirm) }}
        </div>
        {{ render_field(pfp_form.profile_picture) }}

        <div class="login-button-box">
            {{ form.submit(class="login-button", id="login-button-login") }}
            <a href="{{ url_for('auth.login') }}" class="login-button" id="login-button-register">
                LOGIN
            </a>
        </div>
    </form>
</div>
{% endblock %}

website/templates/userpage.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="profile-box">
    <div class="profile-element-data">
        <div class="profile-icon-box">
            <img src="../static/profile_pics/{{user.profile_picture}}" height="200">
        </div>
        <div class="profile-data-box">
            <div class="profile-username">
                {{ user.name }}
            </div>
            <div class="profile-date-text">
                Account created on:
            </div>
            <div class="profile-date">
                {{ user.created_on.strftime('%Y-%m-%d %H:%M') }}
            </div>
        </div>
    </div>
    <div class="profile-line">

    </div>
    <div class="profile-element-info">
        <div class="profile-info-box">
            <div class="profile-info-text">
                HIGH SCORE
            </div>
            <div class="profile-info-number">
                {{ high_score }}
            </div>
        </div>
        <div class="profile-info-box">
            <div class="profile-info-text">
                GAMES PLAYED
            </div>
            <div class="profile-info-number">
                {{ game_count }}
            </div>
        </div>
        <form role="form" method="POST" action="">
            {{render_field(form.comment)}}
            <button class="">
                POST COMMENT
            </button>
        </form>
        {% for comment in comments %}
            <div>
                <a>{{comment.user_from_name}}:</a>
                <a>{{comment.body}}</a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/users.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block content %}

<div class="users-box">
    <div class="users-title">
        USERS
    </div>
    <div class="users-line"></div>
    
    <form class="users-search-box" role="form" method="post" action="">
        <div class="users-search-input">
            {{render_field(form.search)}}
        </div>
        <button class="users-search-button" type="submit">SEARCH</button>
    </form>

    <table class="users-table">
        <thead class="users-table-head">
            <tr>
                <th>ID</th>
                <!-- <th>Email</th> -->
                <th>Username</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <!-- <td>{{ user.email }}</td> -->
                <td><a class="users-profilelink" href="{{ url_for('views.userpage', userid=user.id) }}">{{ user.name }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}